/***************************************************************/
/*                                                             */
/*      PROJECT NAME :  test                                   */
/*      FILE         :  test.cpp                               */
/*      DESCRIPTION  :  Main Program                           */
/*      CPU SERIES   :  RX600                                  */
/*      CPU TYPE     :  RX62T                                  */
/*                                                             */
/*      This file is generated by e2 studio.                   */
/*                                                             */
/***************************************************************/                              

/***********************************************************************/
/*                                                                     */
/*  FILE        :Main.c or Main.cpp                                    */
/*  DATE        :Tue, Oct 31, 2006                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :                                                      */
/*                                                                     */
/*  NOTE:THIS IS A TYPICAL EXAMPLE.                                    */
/*                                                                     */
/***********************************************************************/
#include "iodefine.h"
#include <stdarg.h>

#define FRONT_RIGHT_WALL 2500
#define LED_B PORTB.DR.BIT.B5
#define LED_R PORTB.DR.BIT.B6
#define LED_G PORTB.DR.BIT.B7

#define WAITTIME 5

volatile long time = 0;
volatile long sensor_now = 0;
volatile char data[17];

void interrupt_CMT0(){
	sensor_now = S12AD0.ADDR3;
	time ++;
	S12AD0.ADCSR.BIT.ADST = 1;
}

void wait_miri_second(int i){
	int start = time;
	while(time - start < i){ }
	return;
}

void put1byte(char t){
	SCI1.TDR = t;
	while(SCI1.SSR.BIT.TEND == 0){}
}

void putnbyte(char *t, int len){
	int c=0;
	for(c=0; c<len; c++){
		put1byte(t[c]);
	}
}

int myprintf(const char *fmt, ...){
	static char buffer[100];
	int len;

	va_list ap;//
	va_start(ap, fmt);//omajinai

	len = vsprintf(buffer, fmt, ap);//データの長さを識別
	putnbyte(buffer, len);
	va_end(ap);
	return len;
}

char waitIR(){
	unsigned long log = 0;

	while(1){
		log = log << 1;
		log &= 4095;	//下12桁
		log += (sensor_now > FRONT_RIGHT_WALL) ? 1 : 0;
		wait_miri_second(WAITTIME);

		if(log == 4080) return 0;
	}
}


void getIRdata(){
	char parity = 0;
	int i=0, j=0;

	waitIR();

	for(i=0; i<4; i++){
		data[0] = data[0] << 1;
		data[0] += (sensor_now > FRONT_RIGHT_WALL) ? 1 : 0;
		wait_miri_second(WAITTIME);
	}
	for(i=0; i<data[0]; i++){
		for(j=0; j<4; j++){
			data[i+1] = data[i+1] << 1;
			data[i+1] += (sensor_now > FRONT_RIGHT_WALL) ? 1 : 0;
			wait_miri_second(WAITTIME);
		}
	}

	for(i=0; i<4; i++){
		parity = parity << 1;
		parity += (sensor_now > FRONT_RIGHT_WALL) ? 1 : 0;
		wait_miri_second(WAITTIME);
	}
	for(i=0; i<data[0]; i++){
		parity += data[i+1];
		parity &= 15;
		wait_miri_second(WAITTIME);
	}
//	if(parity != 15) data[0] = 0;
	return;
}


void init(){
	SYSTEM.MSTPCRA.BIT.MSTPA15 = 0;
	IEN(CMT0, CMI0) = 0;
	IPR(CMT0, CMI0) = 10;
	CMT0.CMCR.BIT.CKS = 2;		//PCLK/128
	CMT0.CMCR.BIT.CMIE = 1;		//割り込み許可
	CMT0.CMCNT = 0;
	CMT0.CMCOR = 390;
	IR(CMT0, CMI0) = 0;
	IEN(CMT0, CMI0) = 1;
	CMT.CMSTR0.BIT.STR0 = 1;

	SYSTEM.MSTPCRA.BIT.MSTPA17 = 0;
	S12AD0.ADCSR.BIT.ADST = 0;
	S12AD0.ADCSR.BIT.EXTRG = 0;
	S12AD0.ADCSR.BIT.CKS = 3;
	S12AD0.ADCSR.BIT.ADIE = 1;
	S12AD0.ADCSR.BIT.ADCS = 0;
	S12AD0.ADANS.BIT.CH = 3;

	PORTB.DDR.BIT.B5 = 1;
	PORTB.DDR.BIT.B6 = 1;
	PORTB.DDR.BIT.B7 = 1;

	SYSTEM.MSTPCRB.BIT.MSTPB30 = 0;
	SCI1.SMR.BIT.CKS = 0;				//クロック選択
	SCI1.SMR.BIT.MP = 0;
	SCI1.SMR.BIT.STOP = 0;				//ストップビットは1ビット
	SCI1.SMR.BIT.PE = 0;				//パリティ無し
	SCI1.SMR.BIT.CHR = 0;				//8ビット送信
	SCI1.SMR.BIT.CM = 0;				//調歩同期
	SCI1.SCR.BIT.CKE = 0;				//SCKは入出力ポート
	SCI1.SCR.BIT.TEIE = 0;				//割り込みしない
	SCI1.SCR.BIT.TE = 0;				//送信を禁止
	SCI1.SCR.BIT.RE = 0;				//受信を禁止
	SCI1.SCR.BIT.RIE = 0;				//受信割り込みをしない
	SCI1.SCR.BIT.TIE = 0;				//送信割り込みをしない
//	SCI1.BRR = 40;						//ボーレートを38400bpsにする
	SCI1.BRR = 9;					//ボーレートを156290bpsにする
	SCI1.SEMR.BIT.ABCS = 0;
	SCI1.SCR.BIT.TE = 1;				//送信を許可
}

void main(void){
	int i=0;

	/*クロック設定*/
	SYSTEM.SCKCR.BIT.PCK = 1;
	SYSTEM.SCKCR.BIT.ICK = 0;
	init();

	S12AD0.ADCSR.BIT.ADST = 1;

	for(i=0; i<17; i++){ data[i] = 0; }

	LED_R = 1;
	getIRdata();
	LED_R = 0;
	LED_B = 1;

	myprintf("%d, %d, %d, %d\n", data[0], data[1], data[2], data[3]);

	while(1){
//		myprintf("%d\n", S12AD0.ADDR3);
//		wait_miri_second(100);
	}

}


